name: Publish to VSCode Marketplace

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v2.2.0)'
        required: true
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run webpack

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: List VSIX file
        run: ls -la *.vsix

      - name: Get VSIX filename
        id: vsix-name
        run: echo "VSIX_NAME=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Publish to Visual Studio Marketplace
        run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }} --packagePath $(ls *.vsix)