name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - run: |
          npm install
          npm install -g vsce
          npm run test-compile

  build:
    name: Build VSIX package
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run webpack

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: List VSIX file
        run: ls -la *.vsix

      - name: Get VSIX filename
        id: vsix-name
        run: echo "VSIX_NAME=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: ${{ steps.vsix-name.outputs.VSIX_NAME }}
          if-no-files-found: error

  release:
    if: '!contains(github.event.head_commit.message, ''skip ci'') && github.event_name != ''pull_request'''
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.VSCODE_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "Gamunu Balagalla"
          git config user.email "4501687+gamunu@users.noreply.github.com"

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          release-count: "0"
          github-token: ${{ secrets.VSCODE_TOKEN }}

      - name: Download VSIX package
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: ./

      - name: Get VSIX filename
        id: vsix-name
        run: echo "VSIX_NAME=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Create release with assets
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: ${{ steps.vsix-name.outputs.VSIX_NAME }}
          token: ${{ secrets.VSCODE_TOKEN }}
